#!/bin/bash

if [ $# -eq 0 ]
then
    echo "No directory supplied"
else
    for d in $1/*; do
        if [[ -d "$d" && ! -L "$d" ]]; then
            cd "$d"
            if git rev-parse --git-dir > /dev/null 2>&1; then
                if git cherry -v > /dev/null 2>&1; then
                    if [[ `git cherry -v` != "" ]]; then
                        echo "You have un-pushed commits in $d"
                    fi;
                fi;
            fi;
            cd ..
        fi;
    done
fi;

