#!/bin/bash
#
# Find any unstaged changes to git repositories

if [[ "$EUID" -ne 0 ]]; then
  printf "\nNOTE: If you want to search for hidden directories as well, run as root.\n"
fi

if [[ $# -eq 0 ]]; then
  printf "\nNo directory supplied\n"
else
  num_dirs=0
  dirs=""
  # checks for normal and hidden directories
  for d in $1/* .[^.]*; do
    if [[ -d "$d" && ! -L "$d" ]]; then
      cd "$d" > /dev/null 2>&1
      if git rev-parse --git-dir > /dev/null 2>&1; then
        git_status=$(git status)
        if $(echo ${git_status} | grep -v "nothing to commit" &>/dev/null); then
          num_dirs=$(( num_dirs+=1 ))
          dirs=$dirs$d$'\n'
        fi
      fi
      cd ..
    fi
  done
  if [[ $num_dirs -ne 0 ]]; then
    printf "\nFound these changed git repos:"
    printf "\n------------------------------"
    printf "\n$dirs"
    printf -- "------------------------------"
    printf "\nFound $num_dirs changed git repositories!\n"
  fi
fi
