#!/bin/bash
#
# Find git repositories with unpushed commits

if [[ "$EUID" -ne 0 ]]; then
  printf "\nNOTE: If you want to search for hidden directories as well, run as root.\n"
fi

if [[ $# -eq 0 ]]; then
  printf "\nNo directory supplied\n"
else
  num_dirs=0
  dirs=""
  # checks for normal and hidden directories
  for d in $1/* .[^.]*; do
    if [[ -d "$d" && ! -L "$d" ]]; then
      cd "$d"
      if git rev-parse --git-dir > /dev/null 2>&1; then
        if git cherry -v > /dev/null 2>&1; then
          if [[ `git cherry -v` != "" ]]; then
            num_dirs=$(( num_dirs+=1 ))
            dirs=$dirs$d$'\n'
          fi
        fi
      fi
      cd ..
    fi
  done
  if [[ $num_dirs -ne 0 ]]; then
    printf "\nFound these repos with unpushed commits:"
    printf "\n------------------------------"
    printf "\n$dirs"
    printf -- "------------------------------"
    printf "\nFound $num_dirs non-synced git repositories!\n"
  fi
fi
