#!/usr/bin/env bash
#
# Status script for repositories. Combines ncc and npc (implements them but doesn't use them directly)

main() {
  POSITIONAL=()
  if [[ $# -lt 2 ]]; then
    usage && exit
  fi
  while [[ $# -gt 0 ]]; do
    key=$1
    if [[ $key == -d ]]; then
      dir=$2
      shift
    elif [[ $key == -ncc ]]; then
      ncc=true
    elif [[ $key == -npc ]]; then
      npc=true
    elif [[ $key == -h ]]; then
      usage && exit
    fi
    shift
  done
  set -- ${POSITIONAL[@]}

  run
}

usage() {
  printf "\nUsage: $0 [-d] [-ncc] [-npc] -[h]"
  printf "\n   -d      Recursively check for ncc/npc from supplied directory."
  printf "\n   -ncc    Check for Not Commited Changes."
  printf "\n   -npc    Check for Not Pushed Commits."
  printf "\n   -h      Print usage.\n"
}

run() {
  if [[ "$EUID" -ne 0 ]]; then
    printf "\nNOTE: If you want to search for hidden directories as well, run as root.\n"
  fi

  num_ncc_dirs=0
  num_npc_dirs=0
  ncc_dirs=""
  npc_dirs=""
  # checks for normal and hidden directories
  for d in $dir/* .[^.]*; do
    if [[ -d "$d" && ! -L "$d" ]]; then
      cd "$d"
      if [[ $ncc ]]; then
        run_ncc
      fi
      if [[ $npc ]]; then
        run_npc
      fi
      cd ..
    fi
  done
  if [[ $num_ncc_dirs -ne 0 ]]; then
    print_ncc
  fi
  if [[ $num_npc_dirs -ne 0 ]]; then
    print_npc
  fi
}

run_ncc() {
  if git rev-parse --git-dir &>/dev/null; then
    git_status=$(git status)
    if $(echo ${git_status} | grep -v "nothing to commit" &>/dev/null); then
      num_ncc_dirs=$(( num_ncc_dirs+=1 ))
      ncc_dirs=$ncc_dirs$d$'\n'
    fi
  fi
}

run_npc() {
  if git rev-parse --git-dir &>/dev/null; then
    if git cherry -v &>/dev/null; then
      if [[ `git cherry -v` != "" ]]; then
        num_npc_dirs=$(( num_npc_dirs+=1 ))
        npc_dirs=$npc_dirs$d$'\n'
      fi
    fi
  fi
}

print_ncc() {
  printf "\nFound $num_ncc_dirs changed git repositories!"
  printf "\n------------------------------"
  printf "\n$ncc_dirs"
  printf -- "------------------------------\n"
}

print_npc() {
  printf "\nFound $num_npc_dirs non-synced git repositories!"
  printf "\n------------------------------"
  printf "\n$npc_dirs"
  printf -- "------------------------------\n"
}

main $@
