#!/usr/bin/env bash
#
# Check if there isn't any code pushed or staged before shutting down

if [[ $# -eq 0 ]]; then
  echo "No directory supplied" >&2
else
  num_dirs=0
  dirs=""
  # checks for normal and hidden directories
  for d in $1/* .[^.]*; do
    if [[ -d "$d" && ! -L "$d" ]]; then
      cd "$d" > /dev/null 2>&1
      if git rev-parse --git-dir > /dev/null 2>&1; then
        GIT_STATUS_OUTPUT="$(git status)"
        if `echo ${GIT_STATUS_OUTPUT} | grep -v "nothing to commit" 1>/dev/null 2>&1`; then
          num_dirs=$((num_dirs+=1))
          dirs=$dirs$d$'\n'
        fi
      fi
      cd ..
    fi
  done
  if [[ $num_dirs == 0 ]]; then
    echo "No changes to stage or commit in $1" >&2
  else
    echo "Found these changed git repos:" >&2
    echo "------------------------------" >&2
    echo "$dirs" >&2
    echo "------------------------------" >&2
    echo "Found $num_dirs changed git repositories!" >&2
  fi
fi

if [[ $# -eq 0 ]]; then
  echo "No directory supplied" >&2
else
  n=0
  # checks for normal and hidden directories
  for d in $1/* .[^.]*; do
    if [[ -d "$d" && ! -L "$d" ]]; then
      cd "$d"
      if git rev-parse --git-dir > /dev/null 2>&1; then
        if git cherry -v > /dev/null 2>&1; then
          if [[ `git cherry -v` != "" ]]; then
            echo "$n. You have un-pushed commits in $d" >&2
            n=$((n+=1))
          fi
        fi
      fi
      cd ..
    fi
  done
fi
