#!/usr/bin/env bash
#
# Check if there isn't any code pushed or staged before shutting down


main() {
  POSITIONAL=()
  while [[ $# -gt 0 ]]; do
    key=$1
    if [[ $key == -f ]]; then
      shutdown -h now
    elif [[ $key == -h ]]; then
      usage && exit
    fi
    shift
  done
  set -- ${POSITIONAL[@]}

  if $(sudo repos -d ~ -ncc -npc &>/dev/null); then
    sudo repos -d ~ -ncc -npc
    printf "\nYou seem to have unsaved changes in some git repos\n"
    read -p "Do you want to continue? [Y/n] " YN
    if [[ ${YN^^} == Y ]]; then
      shutdown -h now
    else
      exit
    fi
  fi
}

usage() {
  printf "\nUsage: $0 [-f] [-h]"
  printf "\n   -d      Force shutdown."
  printf "\n   -h      Print usage.\n"
}

main $@
